import type { TreeNode } from '@vino/dt-design/es/userTree/type'

export const mockTree: TreeNode[] = [
  {
    id: '1',
    name: '安徽网钉企业服务中心',
    type: 0,
    peopleCount: 0,
    avatar: null,
    checked: false,
    children: [
      {
        id: '11',
        name: 'a',
        type: 0,
        peopleCount: 0,
        avatar: null,
        checked: false,
        children: [],
      },
      {
        id: '12',
        name: 'b',
        type: 0,
        peopleCount: 0,
        avatar: null,
        checked: false,
        children: [],
      },
      {
        id: '13',
        name: 'c',
        type: 0,
        peopleCount: 0,
        avatar: null,
        checked: false,
        children: [],
      },
      {
        id: '14',
        name: 'd',
        type: 0,
        peopleCount: 0,
        avatar: null,
        checked: false,
        children: [],
      },
      {
        id: '15',
        name: 'user1',
        type: 1,
        peopleCount: 0,
        avatar: null,
        checked: false,
        children: [],
      },
      {
        id: '16',
        name: 'user2',
        type: 1,
        peopleCount: 0,
        avatar: null,
        checked: false,
        children: [],
      },
      {
        id: '17',
        name: 'user3',
        type: 1,
        peopleCount: 0,
        avatar: null,
        checked: false,
        children: [],
      },
    ],
  },
]
