import type { TreeNode } from './type'

export const mockTree: TreeNode[] = [
  {
    id: '1',
    name: '安徽网钉企业服务中心',
    type: 0,
    peopleCount: 0,
    avatar: null,
    checked: false,
    children: [],
  },

  {
    id: '1',
    name: '安徽网钉企业服务中心',
    type: 0,
    peopleCount: 0,
    avatar: null,
    checked: false,
    children: [],
  },
  {
    id: '1',
    name: '安徽网钉企业服务中心',
    type: 0,
    peopleCount: 0,
    avatar: null,
    checked: false,
    children: [],
  },
  {
    id: '1',
    name: '安徽网钉企业服务中心',
    type: 0,
    peopleCount: 0,
    avatar: null,
    checked: false,
    children: [],
  },
  {
    id: '1',
    name: '安徽网钉企业服务中心',
    type: 0,
    peopleCount: 0,
    avatar: null,
    checked: false,
    children: [],
  },
  {
    id: '1',
    name: '安徽网钉企业服务中心',
    type: 0,
    peopleCount: 0,
    avatar: null,
    checked: false,
    children: [],
  },
  {
    id: '1',
    name: '安徽网钉企业服务中心',
    type: 0,
    peopleCount: 0,
    avatar: null,
    checked: false,
    children: [],
  },
  {
    id: '1',
    name: '安徽网钉企业服务中心',
    type: 0,
    peopleCount: 0,
    avatar: null,
    checked: false,
    children: [],
  },
  {
    id: '1',
    name: '安徽网钉企业服务中心',
    type: 0,
    peopleCount: 0,
    avatar: null,
    checked: false,
    children: [],
  },
  {
    id: '1',
    name: '安徽网钉企业服务中心',
    type: 0,
    peopleCount: 0,
    avatar: null,
    checked: false,
    children: [],
  },
  {
    id: '1',
    name: '安徽网钉企业服务中心',
    type: 0,
    peopleCount: 0,
    avatar: null,
    checked: false,
    children: [],
  },
  {
    id: '1',
    name: '安徽网钉企业服务中心',
    type: 0,
    peopleCount: 0,
    avatar: null,
    checked: false,
    children: [],
  },
  {
    id: '1',
    name: '安徽网钉企业服务中心',
    type: 0,
    peopleCount: 0,
    avatar: null,
    checked: false,
    children: [],
  },
]
